import { useEffect, useMemo, useState } from 'react';
import { Copy, RefreshCw, Search, TicketCheck, Trash2 } from 'lucide-react';
import { programs } from '@/data/programs'; import { supabase } from '@/lib/supabase';
type Voucher={code:string;status:string;expires_at:string;redeemed_at:string|null;value_eur?:number};
type Photo={id:string;submission_id:string;guest_name:string;contact:string;email?:string;whatsapp?:string;program_id:string;program_candidates?:string[];program_name:string;photo_url:string;storage_path?:string;status:string;created_at:string;publish_approved:boolean;guest_vouchers?:Voucher[]};
type Match={id:string;booking_code:string;excursion_date:string;program_name:string;hotel_name:string;guest_names:string;phone:string;match_reason:string};
export default function GuestPhotoAdmin(){const [rows,setRows]=useState<Photo[]>([]),[matches,setMatches]=useState<Record<string,Match[]>>({}),[booking,setBooking]=useState<Record<string,string>>({}),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[code,setCode]=useState(''),[note,setNote]=useState(''),[loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('guest_photos').select('id,submission_id,guest_name,contact,email,whatsapp,program_id,program_candidates,program_name,photo_url,storage_path,status,created_at,publish_approved,guest_vouchers(code,status,expires_at,redeemed_at,value_eur)').order('created_at',{ascending:false});setLoading(false);if(error){setNotice('Betöltési hiba: '+error.message);return}const list=(data||[]) as Photo[];setRows(list);const groups=[...new Map(list.map(x=>[x.submission_id,x])).values()].filter(x=>list.some(y=>y.submission_id===x.submission_id&&y.status==='pending'));const pairs=await Promise.all(groups.map(async r=>{const {data:m}=await supabase.rpc('find_booking_matches',{p_name:r.guest_name,p_phone:r.whatsapp||''});return [r.submission_id,(m||[]) as Match[]] as const}));setMatches(Object.fromEntries(pairs));setBooking(v=>{const n={...v};pairs.forEach(([id,m])=>{if(!n[id]&&m[0])n[id]=m[0].id});return n})};
 useEffect(()=>{void load()},[]);
 const groups=useMemo(()=>{const q=search.toLowerCase().trim();const map=new Map<string,Photo[]>();for(const r of rows){const key=r.submission_id||r.id;const arr=map.get(key)||[];arr.push(r);map.set(key,arr)}return [...map.values()].filter(group=>!q||group.some(r=>(r.guest_name+' '+r.email+' '+r.whatsapp+' '+r.program_name).toLowerCase().includes(q))).sort((a,b)=>new Date(b[0].created_at).getTime()-new Date(a[0].created_at).getTime())},[rows,search]);
 async function setPhoto(r:Photo,ok:boolean){const {error}=await supabase.from('guest_photos').update({publish_approved:ok}).eq('id',r.id);if(error)setNotice('Mentési hiba: '+error.message);else setRows(v=>v.map(x=>x.id===r.id?{...x,publish_approved:ok}:x))}
 async function assign(r:Photo,id:string){const p=programs.find(x=>x.id===id);const {error}=await supabase.from('guest_photos').update({program_id:id,program_name:p?.name||id}).eq('id',r.id);if(error)setNotice('Program mentési hiba.');else setRows(v=>v.map(x=>x.id===r.id?{...x,program_id:id,program_name:p?.name||id}:x))}
 async function claimNotification(submissionId:string){const {data,error}=await supabase.rpc('mark_submission_notified',{p_submission_id:submissionId});return !error&&data===true}
 async function email(r:Photo){const {data:{session}}=await supabase.auth.getSession();if(!session)return false;return (await fetch('/api/send-voucher',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({photo_id:r.id})})).ok}
 async function approve(group:Photo[],value:5|10){const first=group[0],bid=value===10?booking[first.submission_id]||null:null;if(value===10&&!bid){setNotice('10 € kuponhoz válassz egyező foglalást.');return}if(!group.some(x=>x.publish_approved)){setNotice('Legalább egy képet jelölj ki publikálásra.');return}const {data,error}=await supabase.rpc('approve_guest_submission',{p_submission_id:first.submission_id,p_value_eur:value,p_booking_id:bid});if(error){setNotice('Jóváhagyási hiba: '+error.message);return}const v=data?.[0];if(v?.newly_issued){const claimed=await claimNotification(first.submission_id);const sent=claimed?await email(first):true;setNotice(sent?`Jóváhagyva, ${v.value_eur} € kupon kiküldve: ${v.code}`:`Kupon elkészült (${v.code}), e-mail küldési hiba.`)}else setNotice('A teljes feltöltés elbírálva. Ehhez a foglaláshoz/adatokhoz már volt kupon, ezért új kupon és újabb e-mail nem készült.');await load()}
 async function remove(r:Photo){if(!confirm('Biztosan végleg törlöd ezt a képet?'))return;if(r.storage_path)await supabase.storage.from('guest-photos').remove([r.storage_path]);await supabase.from('guest_photos').delete().eq('id',r.id);await load()}
 async function redeem(){const {data,error}=await supabase.rpc('redeem_guest_voucher',{p_code:code.trim(),p_note:note.trim()||null});setNotice(error?'Beváltási hiba: '+error.message:'Kupon beváltva: '+(data?.[0]?.code||code));if(!error){setCode('');setNote('');await load()}}
 return <div className="space-y-6"><div className="flex justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Vendégfotók és kuponok</h2><p className="text-sm text-slate-500">Egy feltöltő egy blokkban · képenkénti moderáció · foglalásellenőrzés.</p></div><button onClick={load} className="border rounded-xl px-3 py-2 h-fit inline-flex gap-2"><RefreshCw size={17}/>{loading?'Betöltés...':'Frissítés'}</button></div>{notice&&<div className="rounded-xl bg-sky-50 border border-sky-200 p-3 text-sm font-semibold">{notice}</div>}
 <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold flex gap-2"><TicketCheck/>Kupon ellenőrzése / beváltása</h3><div className="mt-3 grid md:grid-cols-[1fr_1fr_auto] gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="HP-XXXXXXXX" className="border rounded-xl px-3"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Megjegyzés" className="border rounded-xl px-3"/><button onClick={redeem} className="bg-emerald-600 text-white rounded-xl px-4 py-2 font-bold">Beváltás</button></div></section>
 <div className="relative"><Search className="absolute left-3 top-3" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full border rounded-xl py-2.5 pl-10" placeholder="Keresés..."/></div>
 {groups.map(group=>{const first=group[0],m=matches[first.submission_id]||[],pending=group.some(x=>x.status==='pending');return <section key={first.submission_id} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-3 mb-4"><div><b className="text-lg">{first.guest_name}</b><div className="text-sm text-slate-500">{first.email} · WhatsApp: {first.whatsapp}</div><div className="text-xs mt-1 font-bold text-sky-700">1 beküldés · {group.length} feltöltött kép</div></div>{pending&&<div className={`rounded-xl p-3 text-sm ${m.length?'bg-emerald-50 text-emerald-900':'bg-amber-50 text-amber-900'}`}><b>{m.length?'✓ Van egyező korábbi foglalás':'⚠ Nincs egyező korábbi foglalás'}</b>{m.length>0&&<select value={booking[first.submission_id]||''} onChange={e=>setBooking(v=>({...v,[first.submission_id]:e.target.value}))} className="block mt-2 max-w-md border rounded-lg bg-white p-2">{m.map(x=><option key={x.id} value={x.id}>{x.excursion_date} · {x.program_name} · {x.guest_names.replace(/\n/g,', ')} · {x.match_reason}</option>)}</select>}</div>}</div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{group.map(r=><div key={r.id} className={`rounded-xl border p-2 ${r.publish_approved?'border-emerald-400 bg-emerald-50':'bg-slate-50'}`}><img src={r.photo_url} className="w-full aspect-square object-cover rounded-lg"/><select value={r.program_id} onChange={e=>assign(r,e.target.value)} className="mt-2 w-full border rounded-lg p-2 text-xs">{(r.program_candidates?.length?r.program_candidates:[r.program_id]).map(id=><option key={id} value={id}>{programs.find(p=>p.id===id)?.name||id}</option>)}</select>{pending&&<div className="grid grid-cols-2 gap-1 mt-2"><button onClick={()=>setPhoto(r,true)} className="bg-emerald-600 text-white rounded-lg p-2 text-xs font-bold">Mehet ki ✓</button><button onClick={()=>setPhoto(r,false)} className="bg-slate-200 rounded-lg p-2 text-xs font-bold">Ne menjen ki</button></div>}<button onClick={()=>remove(r)} className="mt-2 w-full text-red-700 text-xs font-bold inline-flex justify-center gap-1"><Trash2 size={14}/>Kép törlése</button></div>)}</div>
 {pending&&<div className="mt-4 flex flex-wrap gap-2">{m.length>0&&<button onClick={()=>approve(group,10)} className="bg-emerald-600 text-white rounded-xl px-5 py-3 font-bold">Feltöltés jóváhagyása + 10 € kupon</button>}<button onClick={()=>approve(group,5)} className="bg-sky-600 text-white rounded-xl px-5 py-3 font-bold">Feltöltés jóváhagyása + 5 € kupon</button><span className="text-xs text-slate-500 self-center">A nem publikálható képek nem akadályozzák a kupon kiadását.</span></div>}</section>})}</div>
}