import { useEffect, useMemo, useState } from 'react';
import { Copy, RefreshCw, Search, TicketCheck, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
type Voucher={code:string;status:string;expires_at:string;redeemed_at:string|null};
type Row={id:string;guest_name:string;contact:string;email?:string;whatsapp?:string;program_id?:string;program_candidates?:string[];program_name:string;photo_url:string;storage_path?:string;status:string;created_at:string;voucher_sent_at?:string|null;voucher_eligibility?:string;duplicate_notice_sent_at?:string|null;guest_vouchers?:Voucher[]};
export default function GuestPhotoAdmin(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[code,setCode]=useState(''),[note,setNote]=useState('');
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('guest_photos').select('id,guest_name,contact,email,whatsapp,program_id,program_candidates,program_name,photo_url,storage_path,status,created_at,voucher_sent_at,voucher_eligibility,duplicate_notice_sent_at,guest_vouchers(code,status,expires_at,redeemed_at)').order('created_at',{ascending:false});setLoading(false);if(error)setNotice('A vendégfotók betöltése nem sikerült.');else setRows((data||[]) as Row[])};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(r=>(r.guest_name+' '+r.contact+' '+r.program_name+' '+(r.guest_vouchers?.[0]?.code||'')).toLowerCase().includes(q)):rows},[rows,search]);
 async function sendVoucherEmail(r:Row){const {data:{session}}=await supabase.auth.getSession();if(!session)return false;const response=await fetch('/api/send-voucher',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({photo_id:r.id})});return response.ok}
 async function assignProgram(r:Row,programId:string){const p=(await import('@/data/programs')).programs.find(x=>x.id===programId);const {error}=await supabase.from('guest_photos').update({program_id:programId,program_name:p?.name||programId}).eq('id',r.id);if(error)setNotice('A program hozzárendelése nem sikerült.');else await load()}
 async function duplicateNotice(r:Row){const {data:{session}}=await supabase.auth.getSession();if(!session)return false;const x=await fetch('/api/send-duplicate-voucher-notice',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({photo_id:r.id})});return x.ok}
 async function approve(r:Row){setNotice('');const {data,error}=await supabase.rpc('issue_guest_voucher',{p_photo_id:r.id});if(error){setNotice('A jóváhagyás nem sikerült: '+error.message);return}const v=data?.[0];if(v?.newly_issued){const sent=await sendVoucherEmail(r);setNotice(sent?'Jóváhagyva, a 10 €-s kupon e-mail automatikusan kiküldve: '+v.code:'A kupon elkészült ('+v.code+'), de az e-mail küldése hibázott.')}else{const sent=await duplicateNotice(r);setNotice(sent?'A kép jóváhagyva. A rendszer jelezte a vendégnek e-mailben, hogy ezekkel az adatokkal korábban már kapott kupont, ezért új kupon nem jár.':'A kép jóváhagyva, új kupon nem jár. A tájékoztató e-mail küldése hibázott.')}await load()}
 async function removePhoto(r:Row){const voucher=r.guest_vouchers?.[0];const warning=voucher?'Biztosan végleg törlöd ezt a képet? A hozzá tartozó '+voucher.code+' kupon AZONNAL ÉRVÉNYTELEN lesz.':'Biztosan végleg törlöd ezt a vendégfotót?';if(!confirm(warning))return;setNotice('');const {data,error}=await supabase.rpc('delete_guest_photo_and_invalidate_voucher',{p_photo_id:r.id});if(error){setNotice('A törlés nem sikerült: '+error.message);return}const path=data?.[0]?.storage_path||r.storage_path;if(path){const {error:storageError}=await supabase.storage.from('guest-photos').remove([path]);if(storageError)console.warn('Orphan guest photo object',storageError)}setRows(v=>v.filter(x=>x.id!==r.id));const vc=data?.[0]?.voucher_code||voucher?.code;setNotice(vc?'A kép törölve, a '+vc+' kupon érvénytelenítve.':'A kép törölve.');await load()}
 async function reject(id:string){if(!confirm('Biztosan elutasítod ezt a képet?'))return;const {error}=await supabase.from('guest_photos').update({status:'rejected',reviewed_at:new Date().toISOString()}).eq('id',id);if(error)setNotice('Az elutasítás nem sikerült.');else await load()}
 async function redeem(){if(!code.trim())return;setNotice('');const {data,error}=await supabase.rpc('redeem_guest_voucher',{p_code:code.trim(),p_note:note.trim()||null});if(error){setNotice(error.message.includes('already redeemed')?'Ez a kupon már fel lett használva.':error.message.includes('expired')?'Ez a kupon lejárt.':error.message.includes('invalid voucher')?'Nincs ilyen kupon.':'A beváltás nem sikerült.');return}setNotice('Kupon beváltva: '+(data?.[0]?.code||code.toUpperCase()));setCode('');setNote('');await load()}
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Vendégfotók és kuponok</h2><p className="text-sm text-slate-500">Jóváhagyás, kuponkiadás, ellenőrzés és egyszeri beváltás.</p></div><button onClick={()=>load()} className="border rounded-xl px-3 py-2 inline-flex gap-2"><RefreshCw size={17}/>{loading?'Betöltés...':'Frissítés'}</button></div>{notice&&<div className="rounded-xl bg-sky-50 border border-sky-200 p-3 text-sm font-semibold text-sky-900">{notice}</div>}
 <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold flex items-center gap-2"><TicketCheck className="text-emerald-600"/>Kupon ellenőrzése / beváltása</h3><div className="mt-3 grid md:grid-cols-[1fr_1fr_auto] gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="HP-XXXXXXXX" className="border rounded-xl px-3 py-2 uppercase"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Megjegyzés (opcionális)" className="border rounded-xl px-3 py-2"/><button onClick={redeem} className="bg-emerald-600 text-white font-bold rounded-xl px-4 py-2">Beváltás</button></div></section>
 <div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Keresés név, elérhetőség, program vagy kuponkód alapján..." className="w-full border rounded-xl py-2.5 pl-10 pr-3"/></div>
 <div className="space-y-3">{filtered.map(r=>{const v=r.guest_vouchers?.[0];return <article key={r.id} className="border rounded-2xl p-3 md:p-4 bg-white flex flex-col md:flex-row gap-4"><img src={r.photo_url} className="w-full md:w-28 h-48 md:h-28 object-cover rounded-xl"/><div className="flex-1 text-sm"><b className="text-base">{r.guest_name}</b><div className="text-slate-500">{r.email||r.contact}{r.whatsapp?' · WhatsApp: '+r.whatsapp:''}</div><div className="mt-2"><label className="text-xs font-bold text-slate-500">Kép programja:</label><select value={r.program_id||''} onChange={e=>assignProgram(r,e.target.value)} className="ml-2 rounded-lg border px-2 py-1 text-xs">{(r.program_candidates?.length?r.program_candidates:[r.program_id]).filter(Boolean).map(id=><option key={id} value={id}>{id}</option>)}</select><span className="ml-2 text-xs text-slate-500">{r.program_name}</span></div><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{r.status}</span>{r.voucher_eligibility==='already_received'&&<span className="rounded-full bg-amber-100 text-amber-800 px-2 py-1 text-xs font-bold">Már kapott kupont – új kupon nem jár</span>}</div>{v&&<div className="mt-3 rounded-xl bg-emerald-50 p-3"><div className="font-black text-emerald-800 flex items-center gap-2">{v.code}<button title="Másolás" onClick={()=>navigator.clipboard.writeText(v.code)}><Copy size={15}/></button></div><div className="text-xs text-emerald-700">10 € · {v.status} · lejár: {new Date(v.expires_at).toLocaleDateString('hu-HU')}{v.redeemed_at?' · beváltva: '+new Date(v.redeemed_at).toLocaleDateString('hu-HU'):''}</div></div>}</div><div className="flex md:flex-col gap-2">{r.status==='pending'&&<><button onClick={()=>approve(r)} className="flex-1 bg-emerald-600 text-white px-3 py-2 rounded-xl font-bold">Jóváhagyás + kupon</button><button onClick={()=>reject(r.id)} className="flex-1 bg-amber-50 text-amber-800 px-3 py-2 rounded-xl font-bold">Elutasítás</button></>}<button onClick={()=>removePhoto(r)} className="flex-1 inline-flex items-center justify-center gap-2 bg-red-600 text-white px-3 py-2 rounded-xl font-bold"><Trash2 size={16}/>Kép törlése + kupon érvénytelenítése</button></div></article>})}</div></div>
}