import { useEffect, useMemo, useState } from 'react';
import { Copy, RefreshCw, Search, TicketCheck } from 'lucide-react';
import { supabase } from '@/lib/supabase';
type Voucher={code:string;status:string;expires_at:string;redeemed_at:string|null};
type Row={id:string;guest_name:string;contact:string;email?:string;whatsapp?:string;program_name:string;photo_url:string;status:string;created_at:string;voucher_sent_at?:string|null;guest_vouchers?:Voucher[]};
export default function GuestPhotoAdmin(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[code,setCode]=useState(''),[note,setNote]=useState('');
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('guest_photos').select('id,guest_name,contact,email,whatsapp,program_name,photo_url,status,created_at,voucher_sent_at,guest_vouchers(code,status,expires_at,redeemed_at)').order('created_at',{ascending:false});setLoading(false);if(error)setNotice('A vendégfotók betöltése nem sikerült.');else setRows((data||[]) as Row[])};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?rows.filter(r=>(r.guest_name+' '+r.contact+' '+r.program_name+' '+(r.guest_vouchers?.[0]?.code||'')).toLowerCase().includes(q)):rows},[rows,search]);
 async function sendVoucherEmail(r:Row){const {data:{session}}=await supabase.auth.getSession();if(!session)return false;const response=await fetch('/api/send-voucher',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({photo_id:r.id})});return response.ok}
 async function approve(r:Row){setNotice('');const {data,error}=await supabase.rpc('issue_guest_voucher',{p_photo_id:r.id});if(error){setNotice('A jóváhagyás nem sikerült: '+error.message);return}const v=data?.[0];if(v?.newly_issued){const sent=await sendVoucherEmail(r);setNotice(sent?'Jóváhagyva, a látványos 10 €-s kupon e-mail automatikusan kiküldve: '+v.code:'A kupon elkészült ('+v.code+'), de az e-mail küldése hibázott. Az adminból újraküldhető.')}else{setNotice('A képek jóváhagyva. Ehhez az e-mailhez/WhatsApp számhoz már tartozik kupon ('+(v?.code||'')+'), ezért új kupont nem adtunk.')}await load()}
 async function reject(id:string){if(!confirm('Biztosan elutasítod ezt a képet?'))return;const {error}=await supabase.from('guest_photos').update({status:'rejected',reviewed_at:new Date().toISOString()}).eq('id',id);if(error)setNotice('Az elutasítás nem sikerült.');else await load()}
 async function redeem(){if(!code.trim())return;setNotice('');const {data,error}=await supabase.rpc('redeem_guest_voucher',{p_code:code.trim(),p_note:note.trim()||null});if(error){setNotice(error.message.includes('already redeemed')?'Ez a kupon már fel lett használva.':error.message.includes('expired')?'Ez a kupon lejárt.':error.message.includes('invalid voucher')?'Nincs ilyen kupon.':'A beváltás nem sikerült.');return}setNotice('Kupon beváltva: '+(data?.[0]?.code||code.toUpperCase()));setCode('');setNote('');await load()}
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-extrabold">Vendégfotók és kuponok</h2><p className="text-sm text-slate-500">Jóváhagyás, kuponkiadás, ellenőrzés és egyszeri beváltás.</p></div><button onClick={()=>load()} className="border rounded-xl px-3 py-2 inline-flex gap-2"><RefreshCw size={17}/>{loading?'Betöltés...':'Frissítés'}</button></div>{notice&&<div className="rounded-xl bg-sky-50 border border-sky-200 p-3 text-sm font-semibold text-sky-900">{notice}</div>}
 <section className="rounded-2xl border bg-white p-5"><h3 className="font-bold flex items-center gap-2"><TicketCheck className="text-emerald-600"/>Kupon ellenőrzése / beváltása</h3><div className="mt-3 grid md:grid-cols-[1fr_1fr_auto] gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="HP-XXXXXXXX" className="border rounded-xl px-3 py-2 uppercase"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Megjegyzés (opcionális)" className="border rounded-xl px-3 py-2"/><button onClick={redeem} className="bg-emerald-600 text-white font-bold rounded-xl px-4 py-2">Beváltás</button></div></section>
 <div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Keresés név, elérhetőség, program vagy kuponkód alapján..." className="w-full border rounded-xl py-2.5 pl-10 pr-3"/></div>
 <div className="space-y-3">{filtered.map(r=>{const v=r.guest_vouchers?.[0];return <article key={r.id} className="border rounded-2xl p-3 md:p-4 bg-white flex flex-col md:flex-row gap-4"><img src={r.photo_url} className="w-full md:w-28 h-48 md:h-28 object-cover rounded-xl"/><div className="flex-1 text-sm"><b className="text-base">{r.guest_name}</b><div className="text-slate-500">{r.program_name} · {r.email||r.contact}{r.whatsapp?' · WhatsApp: '+r.whatsapp:''}</div><div className="mt-2"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{r.status}</span></div>{v&&<div className="mt-3 rounded-xl bg-emerald-50 p-3"><div className="font-black text-emerald-800 flex items-center gap-2">{v.code}<button title="Másolás" onClick={()=>navigator.clipboard.writeText(v.code)}><Copy size={15}/></button></div><div className="text-xs text-emerald-700">10 € · {v.status} · lejár: {new Date(v.expires_at).toLocaleDateString('hu-HU')}{v.redeemed_at?' · beváltva: '+new Date(v.redeemed_at).toLocaleDateString('hu-HU'):''}</div></div>}</div>{r.status==='pending'&&<div className="flex md:flex-col gap-2"><button onClick={()=>approve(r)} className="flex-1 bg-emerald-600 text-white px-3 py-2 rounded-xl font-bold">Jóváhagyás + kupon</button><button onClick={()=>reject(r.id)} className="flex-1 bg-red-50 text-red-700 px-3 py-2 rounded-xl font-bold">Elutasítás</button></div>}</article>})}</div></div>
}