import { ArrowLeft, CalendarDays, CreditCard, RefreshCw, ShieldAlert } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useLanguage } from '@/lib/i18n'

export default function Terms() {
  const { language } = useLanguage()
  const en = language === 'en'
  return <main className="min-h-screen bg-slate-50 px-4 pb-16 pt-24 sm:px-6">
    <article className="mx-auto max-w-4xl rounded-3xl border bg-white p-6 shadow-sm sm:p-10">
      <Link to="/ajanlatok" className="mb-7 inline-flex items-center gap-2 text-sm font-bold text-sky-700"><ArrowLeft size={17} />{en ? 'Back to offers' : 'Vissza az ajánlatokhoz'}</Link>
      <h1 className="text-3xl font-black text-slate-900 sm:text-4xl">{en ? 'Terms and Conditions' : 'Általános Szerződési Feltételek'}</h1>
      <p className="mt-3 text-sm text-slate-500">{en ? 'Special terms for prepaid excursion packages' : 'Az előrefizetős programcsomagokra vonatkozó külön feltételek'}</p>
      <div className="mt-9 space-y-8 text-sm leading-7 text-slate-700">
        <Term icon={<CreditCard />} title={en ? '1. Purchase and payment' : '1. Vásárlás és fizetés'}>{en ? 'Discounted packages can be purchased until 31 December 2026 and require full advance payment. A booking becomes valid after the full package price has been received and confirmed. Package discounts cannot be combined with other promotions.' : 'A kedvezményes programcsomagok 2026. december 31-ig vásárolhatók meg, és kizárólag a teljes csomagár előzetes megfizetésével érvényesek. A foglalás a teljes összeg beérkezése és visszaigazolása után válik érvényessé. A csomagkedvezmény más akcióval nem vonható össze.'}</Term>
        <Term icon={<CalendarDays />} title={en ? '2. Validity and choosing dates' : '2. Érvényesség és időpontválasztás'}>{en ? 'The package is valid for 12 months from payment. Exact dates are not required at purchase. Excursion dates must be agreed at least 24–48 hours in advance and depend on available places, weather, operating days and local conditions. Unused excursions expire at the end of the validity period.' : 'A csomag a fizetés napjától számított 12 hónapig használható fel. Vásárláskor nem szükséges pontos programnapokat választani. Az időpontokat legalább 24–48 órával korábban egyeztetni kell, és azok a szabad helyek, az időjárás, a program indulási napjai, valamint a helyi körülmények függvényében biztosíthatók. Az érvényességi idő végéig fel nem használt programok elvesznek.'}</Term>
        <Term icon={<RefreshCw />} title={en ? '3. Changes, cancellations and no-shows' : '3. Időpont-módosítás, lemondás és meg nem jelenés'}>{en ? 'An agreed date may be changed once free of charge if requested at least 24 hours in advance. Cancellation within 24 hours or failure to appear means the affected excursion is treated as used and its price is not refundable. After the statutory withdrawal period, the package price is non-refundable if the guest cancels or does not use the services.' : 'A már egyeztetett programnap legalább 24 órával korábban egy alkalommal díjmentesen módosítható. A program kezdete előtti 24 órán belüli lemondás vagy meg nem jelenés esetén az érintett program felhasználtnak minősül, és annak ára nem téríthető vissza. A jogszabály szerinti elállási időszak letelte után a vendég általi lemondás vagy a szolgáltatás igénybevételének elmulasztása esetén a csomag ára nem visszatéríthető.'}</Term>
        <Term icon={<ShieldAlert />} title={en ? '4. Withdrawal and organiser cancellation' : '4. Elállás és szolgáltatói lemondás'}>{en ? 'Where the statutory right of withdrawal applies, the consumer may withdraw within 14 days of purchase provided that no part of the package has been used. If the guest expressly requests performance within this period, the value of services already supplied may be deducted. If an excursion is cancelled by us or the local organiser, the guest may choose a new date, an equivalent excursion, or a refund of the affected excursion’s package value.' : 'Amennyiben a jogszabály szerinti elállási jog alkalmazandó, a fogyasztó a vásárlástól számított 14 napon belül elállhat, feltéve, hogy a csomag egyetlen elemét sem használta fel. Ha a vendég kifejezetten kéri a teljesítés megkezdését ezen időszakon belül, a már teljesített szolgáltatás arányos értéke levonható. Ha egy programot mi vagy a helyi szolgáltató mond le, a vendég új időpontot, azonos értékű másik programot vagy az érintett program csomagon belüli értékének visszatérítését választhatja.'}</Term>
        <Term icon={<ShieldAlert />} title={en ? '5. Participants and local conditions' : '5. Résztvevők és helyi körülmények'}>{en ? 'Participant names must be provided during booking. A package may not be resold or transferred without prior written approval. Routes, schedules and activity order may change for safety, weather or local operational reasons without affecting the essential content.' : 'A résztvevők nevét a foglaláskor meg kell adni. A csomag előzetes írásos jóváhagyás nélkül nem értékesíthető tovább és nem ruházható át. Biztonsági, időjárási vagy helyi működési okból a program útvonala, időpontja és a programelemek sorrendje úgy változhat, hogy a szolgáltatás lényegi tartalma megmarad.'}</Term>
      </div>
      <p className="mt-10 border-t pt-5 text-xs text-slate-500">{en ? 'Effective: 1 October 2026.' : 'Hatályos: 2026. október 1.'}</p>
    </article>
  </main>
}

function Term({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <section><h2 className="mb-2 flex items-center gap-2 text-lg font-black text-slate-900"><span className="text-sky-600">{icon}</span>{title}</h2><p>{children}</p></section> }
