const json=(res,status,body)=>res.status(status).setHeader('Content-Type','application/json; charset=utf-8').send(JSON.stringify(body));
const supabaseUrl='https://manmcuikrskjstcaqobj.supabase.co'; const publishableKey='sb_publishable_kvbfTNEvGdi8wOwqe9qcMw_EoDo3YMy';
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{error:'POST only'});const auth=req.headers.authorization||'',token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return json(res,401,{error:'Nincs admin munkamenet.'});
 const ur=await fetch(supabaseUrl+'/auth/v1/user',{headers:{apikey:publishableKey,Authorization:'Bearer '+token}});if(!ur.ok)return json(res,401,{error:'Lejárt munkamenet.'});const user=await ur.json();if(user?.app_metadata?.is_admin!==true)return json(res,403,{error:'Nincs admin jogosultság.'});
 const photoId=String(req.body?.photo_id||'');const db=await fetch(supabaseUrl+'/rest/v1/guest_photos?id=eq.'+encodeURIComponent(photoId)+'&select=id,submission_id,guest_name,email,whatsapp,status,voucher_sent_at,guest_vouchers(code,status,expires_at,value_eur)',{headers:{apikey:publishableKey,Authorization:'Bearer '+token}});
 const rows=await db.json();const p=rows?.[0],v=p?.guest_vouchers?.[0];if(!p||p.status!=='approved'||!v||!p.email)return json(res,400,{error:'Nincs küldhető jóváhagyott kupon.'});const key=process.env.RESEND_API_KEY;if(!key)return json(res,500,{error:'RESEND_API_KEY hiányzik.'});
 const expiry=new Date(v.expires_at).toLocaleDateString('hu-HU');const html=`<!doctype html><html><body style="margin:0;background:#eef9ff;font-family:Arial,sans-serif;color:#10233b"><table width="100%" cellpadding="0" cellspacing="0" style="padding:30px 12px"><tr><td align="center"><table width="100%" style="max-width:620px;background:#fff;border-radius:28px;overflow:hidden;box-shadow:0 12px 40px #0c4a6e22"><tr><td style="padding:28px;text-align:center;background:linear-gradient(135deg,#0284c7,#06b6d4);color:#fff"><div style="font-size:14px;font-weight:800;letter-spacing:2px">HURGHADA PROGRAMOK</div><div style="font-size:30px;font-weight:900;margin-top:8px">🎁 ${esc(v.value_eur)} € AJÁNDÉKUTALVÁNY</div></td></tr><tr><td style="padding:30px"><p style="font-size:17px">Szia <b>${esc(p.guest_name)}</b>!</p><p>Köszönjük a feltöltött élményfotókat. A képeidet jóváhagytuk, ezért elkészült a ${esc(v.value_eur)} € értékű kuponod.</p>${Number(v.value_eur)===5?'<div style="margin:16px 0;background:#fff7ed;border-radius:14px;padding:14px;color:#9a3412;font-size:14px"><b>Miért 5 €?</b> A megadott telefonszámhoz nem találtunk korábbi Hurghada Programok foglalást, ezért az 5 €-s vendégfotó kupont kaptad.</div>':''}<div style="margin:26px 0;padding:26px;border:2px dashed #0ea5e9;border-radius:22px;background:#f0f9ff;text-align:center"><div style="font-size:13px;font-weight:800;color:#0369a1">A KUPONKÓDOD</div><div style="font-size:34px;font-weight:900;letter-spacing:3px;color:#0c4a6e;margin:8px 0">${esc(v.code)}</div><div style="font-size:18px;font-weight:800;color:#059669">Érték: ${esc(v.value_eur)} €</div><div style="font-size:13px;color:#64748b;margin-top:8px">Érvényes: ${expiry}</div></div><div style="background:#fff7ed;border-radius:16px;padding:16px;color:#9a3412;font-size:14px"><b>Fontos:</b> a kupon egyszer használható fel, átruházható családtagnak vagy ismerősnek, és több kupon nem vonható össze.</div><p style="margin-top:24px">Foglaláskor küldd el ezt a kuponkódot WhatsAppon, és levonjuk a ${esc(v.value_eur)} € kedvezményt.</p><p style="color:#64748b">Hurghada Programok ☀️</p></td></tr></table></td></tr></table></body></html>`;
 const subject=`🎁 Megérkezett a ${v.value_eur} €-s Hurghada Programok kuponod`;const rr=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json','Idempotency-Key':'guest-voucher-'+v.code},body:JSON.stringify({from:'Hurghada Programok <uzenet@hurghadaprogramok.hu>',to:[p.email],subject,html})});if(!rr.ok){const err=await rr.text();await fetch(supabaseUrl+'/rest/v1/guest_vouchers?code=eq.'+encodeURIComponent(v.code),{method:'PATCH',headers:{apikey:publishableKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({email_status:'failed',email_subject:subject,email_last_error:err})});console.error('voucher email failed',err);return json(res,502,{error:'A kupon elkészült, de az e-mail küldése nem sikerült.'})}const sent=await rr.json();await fetch(supabaseUrl+'/rest/v1/guest_vouchers?code=eq.'+encodeURIComponent(v.code),{method:'PATCH',headers:{apikey:publishableKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({email_status:'sent',email_sent_at:new Date().toISOString(),email_subject:subject,email_provider_id:sent.id||null,email_last_error:null})});
 await fetch(supabaseUrl+'/rest/v1/guest_photos?submission_id=eq.'+encodeURIComponent(p.submission_id),{method:'PATCH',headers:{apikey:publishableKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({voucher_sent_at:new Date().toISOString()})}).catch(()=>{});
 return json(res,200,{ok:true,email:p.email,code:v.code});}